# Generated by Django 3.2.7 on 2021-09-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='A.', max_length=255)),
                ('insertion', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(default='Noniem', max_length=255)),
                ('moderated', models.BooleanField(default=False)),
                ('moderated_by_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ns_zuil.station')),
            ],
        ),
    ]
