# Generated by Django 3.2.7 on 2021-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_zuil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='moderation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='post_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
