# Generated by Django 3.2.7 on 2021-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_zuil', '0003_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='moderated',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
