# Generated by Django 3.2.7 on 2021-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_zuil', '0005_auto_20210930_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='city',
            field=models.CharField(default='Utrecht', max_length=255),
            preserve_default=False,
        ),
    ]
