# Generated by Django 3.2.7 on 2021-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_zuil', '0006_station_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='firstname',
            field=models.CharField(default='A.', max_length=25),
        ),
        migrations.AlterField(
            model_name='message',
            name='insertion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='lastname',
            field=models.CharField(default='Noniem', max_length=25),
        ),
    ]
