# Generated by Django 3.2.7 on 2021-10-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ns_zuil', '0007_auto_20211012_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
